# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20161021_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
