# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 10:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0003_auto_20161025_2200'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photolike',
            unique_together=set([('photo', 'user')]),
        ),
    ]
